[programs.devnet]
solana_anchor = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/venus/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
